module FieldsE

open SolutionTypes

let fieldE4: Field = array2D [ [ w; w; w; w; b; w; w; w; w; w ]
                               [ w; w; w; w; b; w; w; w; w; w ]
                               [ c; c; c; c; c; c; c; c; w; w ]
                               [ w; w; w; w; b; w; w; c; w; w ]
                               [ w; w; w; w; b; w; w; c; w; w ]
                               [ w; w; w; w; b; w; w; c; w; w ]
                               [ c; c; c; c; b; b; b; c; b; w ]
                               [ w; w; w; c; w; w; w; c; w; w ]
                               [ w; w; r; r; r; r; r; c; r; w ]
                               [ b; w; r; c; w; w; w; c; w; w ]
                               [ b; w; r; c; w; w; w; c; w; w ]
                               [ b; w; r; w; w; w; w; c; w; w ]
                               [ b; b; b; b; w; w; w; w; w; w ]
                               [ w; w; r; w; w; w; w; w; w; w ]
                               [ w; w; w; w; w; w; w; w; w; w ]
                               [ w; w; w; w; w; w; w; w; w; w ] ]

let fieldE7: Field = array2D [ [ c; w; c; c; r; c; c; w; c; c ]
                               [ c; w; w; c; r; r; c; w; w; c ]
                               [ w; c; c; r; c; c; r; c; c; w ]
                               [ w; w; c; r; r; c; r; r; c; w ]
                               [ c; c; r; c; c; w; c; c; r; c ]
                               [ w; c; r; r; c; w; w; c; r; r ]
                               [ c; w; c; c; w; c; c; w; c; c ]
                               [ c; w; w; c; w; w; c; w; w; c ]
                               [ w; c; c; r; c; c; r; c; c; w ]
                               [ w; w; c; r; r; c; r; r; c; w ]
                               [ c; c; r; c; c; w; c; c; r; c ]
                               [ r; c; r; r; c; w; w; c; r; r ]
                               [ c; w; c; c; r; c; c; w; c; c ]
                               [ c; w; w; c; r; r; c; w; w; c ]
                               [ r; c; c; w; c; c; r; c; c; r ]
                               [ r; r; c; w; w; c; r; r; c; r ] ]

let fieldE8: Field = array2D [ [ c; w; c; c; r; c; c; w; c; c ]
                               [ c; w; w; c; r; r; w; w; w; c ]
                               [ w; c; c; r; c; c; r; c; c; w ]
                               [ w; w; c; r; r; c; r; r; c; w ]
                               [ c; c; r; c; c; w; c; c; r; w ]
                               [ w; c; r; r; c; w; w; c; r; r ]
                               [ c; c; c; c; w; c; c; w; c; c ]
                               [ w; c; w; c; w; w; c; w; w; c ]
                               [ w; c; c; r; c; c; r; c; c; w ]
                               [ w; w; c; r; r; c; r; r; c; w ]
                               [ c; c; r; c; c; w; c; c; r; c ]
                               [ r; c; r; r; c; w; w; c; r; r ]
                               [ c; c; w; w; r; c; c; w; c; c ]
                               [ c; c; c; w; r; r; c; w; w; c ]
                               [ r; c; c; w; c; c; r; c; c; r ]
                               [ r; r; c; w; w; c; r; r; c; r ] ]

let fieldE9: Field = array2D [ [ c; b; c; c; r; c; c; b; c; c ]
                               [ c; b; b; c; r; r; b; b; b; c ]
                               [ w; c; c; r; c; c; r; c; c; b ]
                               [ w; w; c; r; r; c; r; r; c; b ]
                               [ c; c; r; c; c; w; c; c; r; b ]
                               [ w; c; r; r; c; w; w; c; r; r ]
                               [ c; c; c; c; w; c; c; w; c; c ]
                               [ w; c; w; c; w; w; c; w; w; c ]
                               [ w; c; c; r; c; c; r; c; c; b ]
                               [ w; w; c; r; r; c; r; r; c; b ]
                               [ c; c; r; c; c; w; c; c; r; c ]
                               [ r; c; r; r; c; w; w; c; r; r ]
                               [ c; c; b; b; r; c; c; w; c; c ]
                               [ c; c; c; b; r; r; c; w; w; c ]
                               [ r; c; c; b; c; c; r; c; c; r ]
                               [ r; r; c; b; b; c; r; r; c; r ] ]
